@echo off
REM CAMBIAR AL DIRECTORIO DEL SCRIPT (BACKEND) Y ARRANCAR UVICORN CORRECTAMENTE
cd /d "%~dp0"
REM EJECUTA UVICORN APUNTANDO A MAIN:APP SIN PARÉNTESIS
py -m uvicorn main:app --reload --host 127.0.0.1 --port 8000
